server:
  port: 10900 #程序啟動后的端口,也就是 tomcat 的端口,我們可以自己定义
spring:
  application:
    name: apigateway-zuul-filter #应用名称,别名
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka
  instance:
    prefer-ip-address: true #显示 ip
security:  #配置访问 zuul 的 routes 的时候使用
  user:
    name: user
    password: abc
