server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: file-upload
  http:
    multipart:
      max-file-size: 2000Mb       # Max file size , 默认1M
      max-request-size: 2500Mb    # Max request size , 默认10M