server:
  port: 8901
spring:
  application:
    name: consume-rorder-hystrix
user:
  url: http://localhost:7900/user/
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:10000/eureka
  instance:
    prefer-ip-address: true
