server:
  port: 11900 #程序啟動后的端口,也就是 tomcat 的端口,我們可以自己定义
spring:
  application:
    name: sidecar #应用名称,别名
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka
  instance:
    prefer-ip-address: true #显示 ip
security:  #配置访问 zuul 的 routes 的时候使用
  user:
    name: user
    password: abc
sidecar:
  port: 8060 #配置异构服务的端口, host 必须和当前的sidecar 所在的 host 一致  host 不是机器,是域名
  health-uri: http://localhost:8060/health.json